version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Montar el proyecto en el contenedor
      - ./node_modules:/app/node_modules # Montar node_modules desde tu máquina local
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081" 
    command: npm start
